readingtracker/urls.py
from django.contrib import admin
from django.urls import include,path

from tracker import views as tracker_views

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('tracker.urls')),
	path('accounts/', include('django.contrib.auth.urls')),
    path('signUp/', tracker_views.signUp, name='signUp')
]

tracker/urls.py
from django.urls import path

from . import views

app_name='tracker'

urlpatterns = [
	path('', views.index, name='index'),
	path('addBook/', views.addBook, name='addBook'),
	path('deleteBook/<int:pk>/', views.deleteBook, name='deleteBook'),
	path('moveBook/<int:pk>/', views.moveBook, name='moveBook'),
	path('profile/', views.displayProfile, name='displayProfile'),
	path('deleteAccount/', views.deleteAccount, name='deleteAccount'),
	path('books/', views.showBooks, name='showBooks')

]

tracker/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
	name = models.CharField(max_length=200)
	already_read = models.BooleanField()
	user = models.CharField(max_length=200)
	completed_date_time = models.DateTimeField(null=True, blank=True) 


	def __str__(self):
		return self.name + " " + str(self.already_read)

tracker/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):

	name = forms.CharField(max_length=100 , widget=forms.TextInput(attrs={'class': "form-control mr-1", 'id': "book_input"}))


	class Meta:
		model = Book
		exclude = ['user']

tracker/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

from .models import Book
from .forms import BookForm

from datetime import datetime
import json

# Create your views here.
@login_required
def index(request):
	username = None
	if request.user.is_authenticated:
		username = request.user.get_username()
	book_list = Book.objects.all().filter(user=username).order_by('-completed_date_time')
	# interate through book_list and create subset
	book_list_completed = []
	book_list_remaining = []
	books_completed_per_month = {}
	for book in book_list:
		if book.already_read:
			if book.completed_date_time:
				date_str = book.completed_date_time.strftime("%Y-%m-%d")
				count = books_completed_per_month.get(date_str)
				if count:
					count = count+1
					books_completed_per_month[date_str] = count
				else:
					books_completed_per_month[date_str] = 1
			book_list_completed.append(book)
		else:
			book_list_remaining.append(book)
	form = BookForm()
	context = {
		'book_list_completed' : book_list_completed,
		'book_list_remaining' : book_list_remaining, 
		'book_list_completed_number' : len(book_list_completed),
		'book_list_remaining_number' : len(book_list_remaining), 
		'book_completed_months': json.dumps(list(books_completed_per_month.keys())),
		'book_completed_count': json.dumps(list(books_completed_per_month.values())),
		'form' : form,
		'username' : username,
	}
	return render(request, 'tracker/index.html', context)

@login_required
def showBooks(request):
	username = None
	if request.user.is_authenticated:
		username = request.user.get_username()
	book_list = Book.objects.all().filter(user=username).order_by('-completed_date_time')
	# interate through book_list and create subset
	book_list_completed = []
	book_list_remaining = []
	books_completed_per_month = {}
	for book in book_list:
		if book.already_read:
			if book.completed_date_time:
				date_str = book.completed_date_time.strftime("%Y-%m-%d")
				count = books_completed_per_month.get(date_str)
				if count:
					count = count+1
					books_completed_per_month[date_str] = count
				else:
					books_completed_per_month[date_str] = 1
			book_list_completed.append(book)
		else:
			book_list_remaining.append(book)
	form = BookForm()
	context = {
		'book_list_completed' : book_list_completed,
		'book_list_remaining' : book_list_remaining, 
		'book_list_completed_number' : len(book_list_completed),
		'book_list_remaining_number' : len(book_list_remaining), 
		'book_completed_months': json.dumps(list(books_completed_per_month.keys())),
		'book_completed_count': json.dumps(list(books_completed_per_month.values())),
		'form' : form,
		'username' : username,
	}
	return render(request, 'tracker/books.html', context)

@login_required
def deleteAccount(request):
	username = None
	if request.user.is_authenticated:
		username = request.user.get_username()
	Book.objects.all().filter(user=username).delete()
	User.objects.get(username=username).delete()
	# log out user
	logout(request)
	return redirect('/accounts/login/')


@login_required
def displayProfile(request):
	username = None
	if request.user.is_authenticated:
		username = request.user.get_username()
	# Get profile object using username
	profile = User.objects.get(username=username)
	context = {
		'profile' : profile,
	}
	return render(request, 'tracker/profile.html', context)

@require_POST
def addBook(request):
	newBookForm = BookForm(request.POST)
	if newBookForm.is_valid():
		new_book = newBookForm.save(commit=False)
		new_book.user = request.user.get_username()
		newBookForm.save()
	return redirect('tracker:index')

def deleteBook(request,pk):
	Book.objects.filter(id=pk).delete()
	return redirect('tracker:index')

def moveBook(request,pk):
	book = Book.objects.get(pk=pk)
	book.already_read = not book.already_read
	if book.already_read:
		book.completed_date_time = datetime.now()
	else:
		book.completed_date_time = None
	book.save()
	return redirect('tracker:index')

def login_view(request):
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			return redirect('tracker:index')
	else:
		form = AuthenticationForm()
	return render(request, 'registration/login.html', {'form': form})

def signUp(request):
	if request.method == 'POST':
		form = UserCreationForm(data=request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username=username, password=raw_password)
			login(request, user)
			return redirect('tracker:index')
	else:
		form = UserCreationForm()
	return render(request, 'registration/signUp.html', {'form': form})

	

readingtracker/tracker/templates/tracker/login.html
{% extends 'tracker/base.html' %}

{% block content %}
	<div class="row">
	    <div class="col-sm">
	    </div>
	    <div class="col-sm">
	      <div class="card" style="width: 18rem;">
			<div class="card-header">
			    <h5 class="card-title">Sign in</h5>
			  </div>
			  <div class="card-body">
				    <div class="form-group">
				    	<form action="{% url 'tracker:login' %}" method="post">
							{% csrf_token %}
							{{ form }}
							<input style="margin-top: 5px" class="btn btn-primary" type="submit" id="login_btn" value="Sign in">
						</form>
					</div>
			  </div>
			</div>
	    </div>
	    <div class="col-sm">
	    </div>
  	</div>

{% endblock %}

tracker/templates/tracker/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<title>Reading Tracker</title>
</head>
<body style="background: linear-gradient(#FC7753, white);
  height: 100%;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  position: relative">
	
	<div class="container" style="width: 100%; text-align: center; ">
		{% block content %}
    	{% endblock content %}
	</div>
    <script src="https://kit.fontawesome.com/11adc40d91.js" crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.min.js"></script>
	{% block scripts %}
    {% endblock scripts %}
</body>
</html>

tracker/templates/tracker/books.html
{% extends 'tracker/base.html' %}

{% block content %}
	<h1 class=".display-4" id="welcome-message"  style="color: white; padding-top: 5px">Welcome {{ username }}</h1>
	<a id="home" class="btn btn-outline-light" href="/">Home</a>
	<a id="books" class="btn btn-outline-light" href="/books">Books</a>
	<a id="profile" class="btn btn-outline-light" href="/profile">Profile</a>
	<a id="logout" class="btn btn-outline-light" href="/accounts/logout/">Log Out</a>
    	<form action="{% url 'tracker:addBook' %}" method="post">
    		 <div class="d-flex" style="padding: 5px;">
		    	{% csrf_token %}
		        {{ form.name }}	
				<input type="submit" id="add_book_btn" class="btn btn-success" value="Add">
		    </div>
		</form>
	<div class="row" style="padding: 5px;">
	    <div class="col-sm" >
	    	
			<h5 class=".display-4" style="color: white;">Books Already Read</h5>
	    	<div class="card">
				<div class="card-body">
					{% if book_list_completed %}
						<div>
							<ul class="list-group list-group-flush">
						    {% for book in book_list_completed %}
						        	<li id="{{book.name|cut:" " }}" class="list-group-item">{{ book.name }}
						        		<a class="text-danger" href="{% url 'tracker:deleteBook' book.id %}"><i class="far fa-trash-alt"></i></a>
						        		<a class="text-success" href="{% url 'tracker:moveBook' book.id %}">To Read</a>
						        	</li>
						    {% endfor %}
						    </ul>
						</div>
					{% else %}
					    <p>No books have been added to track</p>
					{% endif %}    
				</div>
			</div>
	    </div>
	    <div class="col-sm">
	    	<h5 class=".display-4" style="color: white;">Books To Read</h5>
	    	<div class="card">
				<div class="card-body">
					{% if book_list_remaining %}
						<div>
							<ul class="list-group list-group-flush">
						    {% for book in book_list_remaining %}
						        	<li id="{{book.name|cut:" " }}" class="list-group-item">{{ book.name }}
						        		<a class="text-danger" href="{% url 'tracker:deleteBook' book.id %}"><i class="far fa-trash-alt"></i></a>
					        			<a class="text-success" href="{% url 'tracker:moveBook' book.id %}">Completed Reading</a>
						        	</li>
						    {% endfor %}
						    </ul>
						</div>
					{% else %}
					    <p>No books have been added to track</p>
					{% endif %}    
				</div>
			</div>
	    </div>
	</div>
{% endblock %}

tracker/templates/tracker/index.html
{% extends 'tracker/base.html' %}

{% block scripts %}
<script type="text/javascript">
$(document).ready(function(){
	const ctx = document.getElementById('completedChart').getContext('2d');
	// get this array from django
	const count = {{book_completed_count|safe }};
	const countLength = count.length;
	//get this array from django
	const monthStr =  {{book_completed_months|safe }};
	const monthArr = [];
	const dataArr = [];
	for (var i = 0; i < countLength; i++) {
		const dateObj = new Date(monthStr[i]);
    	const dataObj = {
    		x: dateObj,
    		y: parseInt(count[i])
    	}
    	monthArr.push(dateObj);
    	dataArr.push(dataObj);
	}
	var chart = new Chart(ctx, {
	    type: 'line',
	    data: {
    		labels: monthArr,
	        datasets: [{
            	backgroundColor: 'rgba(122, 199, 79, 0.2)',
            	borderColor: 'rgba(122, 199, 79, 1.0)',
            	data: dataArr
	        }]
	    },

	    // Configuration options go here
	    options: {
	    	title: {
		        display: true,
		        text: 'Books Completed Per Month',
		        fontColor: 'white'
	      	},
	    	elements: {
		        line: {
		            tension: 0
		        }
		    },
	    	legend: {
	            display: false,
	        },
	    	layout: {
	            padding: {
	                left: 0,
	                right: 25,
	                top: 0,
	                bottom: 0
	            },
	        },
	        scales: {
			    yAxes: [{
			      gridLines: {
			        display: 'false'
			      },
			      ticks: {
                           fontColor: "white",
                           precision: 0    
                       },
			      scaleLabel: {   // To format the scale Lebel
                    display: true,
                    labelString: '# of Books',
                    fontColor:'#ffffff'
                    },
			    }],
			    xAxes: [{
			    	type: 'time',
			    	distribution: 'series',
			    	time: {
	                    displayFormats: {
	                        quarter: 'MMM YYYY'
	                    }
	                },
			      	gridLines: {
			        	display: 'false'
			      	},
			      	ticks: {
                               fontColor: "white",
                           },
			      	scaleLabel: {   // To format the scale Lebel
                                display: false
                            },
			    }],
		  	}
	    }
	});
	
	const ctxTodoChart = document.getElementById('todoChart').getContext('2d');

	//GET THIS FROM DJANGO
	const dataArrTodoChart = [parseInt("{{book_list_completed_number}}"), parseInt("{{book_list_remaining_number}}")];
	const data = {
      labels: ["Completed", "Remaining"],
      datasets: [
        {
          label: "Total Books Completed vs Remaining",
          borderColor: ['rgba(122, 199, 79, 1.0)', 'rgba(228, 87, 46, 1.0)'],
          // 228, 87, 46
          backgroundColor: ['rgba(122, 199, 79, 0.2)', 'rgba(228, 87, 46, 0.2)'],
          data: dataArrTodoChart
        }
      ]
    }

    options =  {
      title: {
        display: true,
        text: 'Total Books Completed vs Still To Read',
        fontColor: 'white'
      },
      layout: {
	            padding: {
	                left: 0,
	                right: 50,
	                top: 5,
	                bottom: 5
	            },
	        },
      legend: {
            display: true,
		    position: "left"
        }
    }

	new Chart(ctxTodoChart, {
    	type: 'doughnut',
    	data: data,
    	options: options
	});
	
});
</script>
{% endblock scripts %}

{% block content %}
	<h1 class=".display-4" id="welcome-message"  style="color: white; padding-top: 5px">Welcome {{ username }}</h1>
	<a id="home" class="btn btn-outline-light" href="/">Home</a>
	<a id="books" class="btn btn-outline-light" href="/books">Books</a>
	<a id="profile" class="btn btn-outline-light" href="/profile">Profile</a>
	<a id="logout" class="btn btn-outline-light" href="/accounts/logout/">Log Out</a>
    	<form action="{% url 'tracker:addBook' %}" method="post">
    		 <div class="d-flex" style="padding: 5px;">
		    	{% csrf_token %}
		        {{ form.name }}	
				<input type="submit" id="add_book_btn" class="btn btn-success" value="Add">
		    </div>
		</form>
	<div class="row" style="padding: 5px;">
	    <div class="col-sm" >
	    	
			<h5 class=".display-4" style="color: white;">Books Already Read</h5>
	    	<div class="card">
				<div class="card-body">
					{% if book_list_completed %}
						<div>
							<ul class="list-group list-group-flush">
						    {% for book in book_list_completed|slice:":4" %}
						        	<li id="{{book.name|cut:" " }}" class="list-group-item">{{ book.name }}
						        		<a class="text-danger" href="{% url 'tracker:deleteBook' book.id %}"><i class="far fa-trash-alt"></i></a>
						        		<a class="text-success" href="{% url 'tracker:moveBook' book.id %}">To Read</a>
						        	</li>
						    {% endfor %}
						    </ul>
						</div>
						<a style="color: grey;" href="{% url 'tracker:showBooks' %}">See More...</a>
					{% else %}
					    <p>No books have been added to track</p>
					{% endif %}    
				</div>
			</div>
	    </div>
	    <div class="col-sm">
	    	<h5 class=".display-4" style="color: white;">Books To Read</h5>
	    	<div class="card">
				<div class="card-body">
					{% if book_list_remaining %}
						<div>
							<ul class="list-group list-group-flush">
						    {% for book in book_list_remaining|slice:":4" %}
						        	<li id="{{book.name|cut:" " }}" class="list-group-item">{{ book.name }}
						        		<a class="text-danger" href="{% url 'tracker:deleteBook' book.id %}"><i class="far fa-trash-alt"></i></a>
					        			<a class="text-success" href="{% url 'tracker:moveBook' book.id %}">Completed Reading</a>
						        	</li>
						    {% endfor %}
						    </ul>
						</div>
						<a style="color: grey;" href="{% url 'tracker:showBooks' %}">See More...</a>
					{% else %}
					    <p>No books have been added to track</p>
					{% endif %}    
				</div>
			</div>
	    </div>
	</div>
	<h1 class=".display-4" id="dashboard-message"  style="color: white; padding-top: 5px">Dashboard</h1>
	<div class="row">
		<div class="col-sm-6" >
			<canvas style="width: 100%; background-color: #11151C; border-radius: 20px;" id="completedChart"></canvas>
		</div>
		<div class="col-sm-6" >
			<canvas style="width: 100%; background-color: #11151C; border-radius: 20px;" id="todoChart"></canvas>
		</div>
	</div>



{% endblock %}

tracker/templates/tracker/profile.html
{% extends 'tracker/base.html' %}


{% block content %}
<div class="row" style="padding: 100px">
	    <div class="col-sm-3">
	    </div>
	    <div class="col-sm-6">
	    	<div class="row-sm-12">
	    	</div>
	    	<div class="row-sm-12 my-auto">
	    		<a id="home" class="btn btn-outline-light" href="/">Home</a>
    			<a id="books" class="btn btn-outline-light" href="/books">Books</a>
				<a id="profile" class="btn btn-outline-light" href="/profile">Profile</a>
				<a id="logout" class="btn btn-outline-light" href="/accounts/logout/">Log Out</a>
			    <h1 id="profile-message" class="display-2" style="color: white;">Profile</h5>
	    		<div class="card mx-auto" style="width: 18rem;">
					<!-- <div class="card-header">
				    </div> -->
				  	<div class="card-body">
				  		<p>
				  			<label>User Name:</label> 
				  		{{ profile.username }} <br>
				  			<label>Date Joined:</label> 	
					    {{ profile.date_joined }} <br>
				  		</p>
					    <a class="text-danger" href="{% url 'tracker:deleteAccount' %}" onclick="return confirm('Are you sure? This will delete all your saved book information.')">Delete Account</a> <br>
					    <a style="color: grey;" href="/">Back</a>
				    </div>
				</div>
	    	</div>
	    	<div class="row-sm-12">
	    	</div>
	    </div>
	    <div class="col-sm-3">
	    </div>
  	</div>
{% endblock %}